[workspace]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
platforms = ["osx-arm64", "win-64", "linux-64"]
preview = ["pixi-build"]

[dependencies]
pydantic = ">=2.8.2,<3"
ruff = "*"
pixi-build-ros = { path = "." }

[environments]
default = { features = [], solve-group = "default" }
test = { features = ["test"], solve-group = "default" }

[feature.test.tasks]
test = "pytest tests"

[feature.test.dependencies]
pixi-pycharm = ">=0.0.8,<0.1"
pytest = "*"
py-pixi-build-backend = { path = "../../py-pixi-build-backend" }

[package.build.backend]
name = "pixi-build-python"
version = "*"

[package]
name = "pixi-build-ros"
version = "0.1.3"

[package.host-dependencies]
hatchling = "*"

[package.run-dependencies]
rosdistro = "*"
pydantic = ">=2.8.2,<3"
catkin_pkg = "*"
pyyaml = "*"
pixi-build-api-version = ">=2,<3"
# should be added to `py-pixi-build-backend`
typing-extensions = "*"
#py-pixi-build-backend = "*"
py-pixi-build-backend = { path = "../../py-pixi-build-backend" }
